# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI_PopUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI_PopUp

  pod 'ExytePopupView'


  target 'SwiftUI_PopUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUI_PopUpUITests' do
    # Pods for testing
  end

end
